name: Patch Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up 
      run: |
       sudo apt update
       sudo apt install tar zstd
       sudo -E apt-get -qq install build-essential clang llvm flex g++ gawk gcc-multilib gettext \
       git libncurses5-dev libssl-dev python3-distutils python3-pyelftools python3-setuptools \
       python3-dev python3-pip rsync unzip zlib1g-dev swig aria2 jq subversion qemu-utils ccache rename \
       libelf-dev device-tree-compiler libgnutls28-dev coccinelle libgmp3-dev libmpc-dev libfuse-dev gcc-multilib
        pip3 install --user -U pylibfdt
        
       curl https://downloads.immortalwrt.org/snapshots/targets/rockchip/armv8/immortalwrt-imagebuilder-rockchip-armv8.Linux-x86_64.tar.zst
       tar -I zstd -xvf immortalwrt-imagebuilder-rockchip-armv8.Linux-x86_64.tar.zst
       cd immortalwrt-imagebuilder-rockchip-armv8.Linux-x86_64
       make image PROFILE="friendlyarm_nanopi-r2s" PACKAGES="autocore automount base-files block-mount busybox ca-bundle default-settings-chn dnsmasq-full dropbear fdisk firewall4 fstools ipv6helper kmod-gpio-button-hotplug kmod-nf-nathelper kmod-nf-nathelper-extra kmod-nft-offload libc libgcc libustream-openssl logd luci luci-app-cpufreq luci-app-opkg luci-compat luci-lib-base luci-lib-ipkg mkf2fs mtd netifd nftables opkg partx-utils ppp ppp-mod-pppoe procd procd-seccomp procd-ujail uboot-envtools uci uclient-fetch urandom-seed urngd  luci-app-adguardhome luci-app-advanced-reboot luci-app-alist luci-app-aria2 luci-app-ddns luci-app-filebrowser-go luci-app-homeproxy luci-app-ttyd luci-app-upnp luci-app-zerotier luci-theme-argon drill ddns-scripts-cloudflare luci-i18n-alist-zh-cn luci-i18n-aria2-zh-cn luci-i18n-cpufreq-zh-cn luci-i18n-ddns-zh-cn luci-i18n-firewall-zh-cn luci-i18n-opkg-zh-cn luci-i18n-ttyd-zh-cn luci-i18n-upnp-zh-cn luci-i18n-zerotier-zh-cn" CONFIG_TARGET_ROOTFS_EXT4=y CONFIG_TARGET_ROOTFS_SQUASHFS=n CONFIG_TARGET_IMAGES_SQUASHFS=n CONFIG_TARGET_IMAGES_GZIP=n                          
       ls bin/targets/rockchip/armv8
