name: Patch Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up 
      run: |
       sudo echo -e "
         # 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
         deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy main restricted universe multiverse
         # deb-src http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy main restricted universe multiverse
         deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse
         # deb-src http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse
         deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse
         # deb-src http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse

         # 以下安全更新软件源包含了官方源与镜像站配置，如有需要可自行修改注释切换
         deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
         # deb-src http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse

         # 预发布软件源，不建议启用
         # deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-proposed main restricted universe multiverse
         # # deb-src http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-proposed main restricted universe multiverse
        " | sudo tee /etc/apt/sources.list

       sudo apt update
       sudo apt install tar zstd
       sudo apt-get install -y build-essential flex bison clang-17 cmake g++ gawk gcc-multilib g++-multilib gettext git libfuse-dev libncurses5-dev libssl-dev python3 python3-pip python3-ply python3-distutils python3-pyelftools rsync unzip zlib1g-dev file wget subversion patch upx-ucl autoconf automake curl asciidoc binutils bzip2 lib32gcc-s1 libc6-dev-i386 uglifyjs msmtp texinfo libreadline-dev libglib2.0-dev xmlto libelf-dev libtool autopoint antlr3 gperf ccache swig coreutils haveged scons libpython3-dev rename qemu-utils
       curl https://downloads.immortalwrt.org/snapshots/targets/rockchip/armv8/immortalwrt-imagebuilder-rockchip-armv8.Linux-x86_64.tar.zst
       tar -I zstd -xvf immortalwrt-imagebuilder-rockchip-armv8.Linux-x86_64.tar.zst
       cd immortalwrt-imagebuilder-rockchip-armv8.Linux-x86_64
       make image PROFILE="friendlyarm_nanopi-r2s" PACKAGES="autocore automount base-files block-mount busybox ca-bundle default-settings-chn dnsmasq-full dropbear fdisk firewall4 fstools ipv6helper kmod-gpio-button-hotplug kmod-nf-nathelper kmod-nf-nathelper-extra kmod-nft-offload libc libgcc libustream-openssl logd luci luci-app-cpufreq luci-app-opkg luci-compat luci-lib-base luci-lib-ipkg mkf2fs mtd netifd nftables opkg partx-utils ppp ppp-mod-pppoe procd procd-seccomp procd-ujail uboot-envtools uci uclient-fetch urandom-seed urngd  luci-app-adguardhome luci-app-advanced-reboot luci-app-alist luci-app-aria2 luci-app-ddns luci-app-filebrowser-go luci-app-homeproxy luci-app-ttyd luci-app-upnp luci-app-zerotier luci-theme-argon drill ddns-scripts-cloudflare luci-i18n-alist-zh-cn luci-i18n-aria2-zh-cn luci-i18n-cpufreq-zh-cn luci-i18n-ddns-zh-cn luci-i18n-firewall-zh-cn luci-i18n-opkg-zh-cn luci-i18n-ttyd-zh-cn luci-i18n-upnp-zh-cn luci-i18n-zerotier-zh-cn" CONFIG_TARGET_ROOTFS_EXT4=y CONFIG_TARGET_ROOTFS_SQUASHFS=n CONFIG_TARGET_IMAGES_SQUASHFS=n CONFIG_TARGET_IMAGES_GZIP=n                          
       ls bin/targets/rockchip/armv8
